micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/todo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: kushagra
    password: '123456'
    schema-generate: CREATE_DROP
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
